In [ ]:
#bai1
try:
    a = float(input("Nhập số thứ nhất a: "))
    b = float(input("Nhập số thứ hai b: "))
except ValueError:
    print("Vui lòng nhập số hợp lệ!")
    exit()
tong = a + b
hieu = a - b
tich = a * b

if b != 0:
    thuong = a / b
else:
    thuong = "Không thể chia cho 0"
print(f"\nKết quả:")
print(f"Tổng: {a} + {b} = {tong}")
print(f"Hiệu: {a} - {b} = {hieu}")
print(f"Tích: {a} * {b} = {tich}")
print(f"Thương: {a} / {b} = {thuong}")

Nhập số thứ nhất a: 2
Nhập số thứ hai b: 5

Kết quả:
Tổng: 2.0 + 5.0 = 7.0
Hiệu: 2.0 - 5.0 = -3.0
Tích: 2.0 * 5.0 = 10.0
Thương: 2.0 / 5.0 = 0.4


In [ ]:
#bai2
s = "Hello World"
result = s[2:5]
print(result)

llo


In [ ]:
#bai3
s = "   Hello World  "
s_stripped = s.strip()
s_upper = s_stripped.upper()
s_lower = s_stripped.lower()
s_replaced = s_stripped.replace('H', 'J')
print(s_stripped)
print(s_upper)
print(s_lower)
print(s_replaced)

Hello World
HELLO WORLD
hello world
Jello World


In [ ]:
#bai4
a = float(input())
b = float(input())
if a > b:
    print("Hello World!")

5
4
Hello World!


In [ ]:
#bai5
a = float(input())
b = float(input())
if a == b:
    print("Yes")
else:
    print("No")

5
7
No


In [ ]:
#bai6
a = float(input())
b = float(input())
if a == b:
    print(1)
elif a > b:
    print(2)
else:
    print(3)

2
3
3


In [ ]:
#bai7
a = float(input())
b = float(input())
d = float(input())
if a == b and b == d:
    print("Hello World!")

2
2
2
Hello World!


In [ ]:
#b8
a = float(input())
b = float(input())
d = float(input())
c = float(input())
if a == b or c == d:
    print("Hello World!")

1
3
4
5


In [ ]:
#b9
a = float(input())
b = float(input())
print('Yes'if a>b else 'No')


6
5
Yes


In [ ]:
#b10
a = float(input())
b = float(input())
print("A") if a > b else print("=") if a == b else print("B")

3
2
A


In [ ]:
#b11
n = int(input("Nhập số lượng phần tử n: "))
a = list(map(int, input("Nhập các phần tử của mảng a (cách nhau bởi dấu cách): ").split()))
b = [x for x in a if x % 2 == 0]
print("Mảng b (các phần tử chẵn):", b)

Nhập số lượng phần tử n: 10
Nhập các phần tử của mảng a (cách nhau bởi dấu cách): 3 4 5 6 7 78 8 9 10 11 12 
Mảng b (các phần tử chẵn): [4, 6, 78, 8, 10, 12]


In [ ]:
#b12
total = 0
for i in range(1000):
    if i % 3 == 0 or i % 5 == 0:
        total += i
print(total)


233168


In [ ]:
#bt 13
a = list(map(int, input("Nhập mảng a: ").split()))
b = list(map(int, input("Nhập mảng b: ").split()))

min_len = min(len(a), len(b))
result = [a[i] + b[i] for i in range(min_len)]

if len(a) > len(b):
    result.extend(a[min_len:])
elif len(b) > len(a):
    result.extend(b[min_len:])

print("Mảng kết quả:", result)


Nhập mảng a: 2 3 4 5 6 7 8 9 10
Nhập mảng b:  9 9 5 4 6 7 8 9 88 1 8
Mảng kết quả: [11, 12, 9, 9, 12, 14, 16, 18, 98, 1, 8]


In [3]:
#b14
import numpy as np

#mảng a
m, n = 4, 5
a = np.random.randint(1, 100, (m, n))
print("Mảng a:\n", a)
#ptử dòng k
k = 1
print(f"Dòng {k}:", a[k])
#ptử cột k
k = 2
print(f"Cột {k}:", a[:, k])
#dòng có tổng lớn nhất
tong = [sum(a[i]) for i in range(m)]
print("Dòng có tổng lớn nhất:", np.argmax(tong))
#cột có tích nhỏ nhất
tich = [np.prod(a[:, j]) for j in range(n)]
print("Cột có tích nhỏ nhất:", np.argmin(tich))
#Phần tử dòng chẵn, cột lẻ
print("Dòng chẵn, cột lẻ:\n", a[::2, 1::2])
#TBC phần tử chẵn thuộc dòng lẻ
chan_dong_le = a[1::2][a[1::2] % 2 == 0]
print("TB chẵn ở dòng lẻ:", chan_dong_le.mean())
#tbc phần tử thuộc biên
bien = np.concatenate([a[0], a[-1], a[1:-1, 0], a[1:-1, -1]])
print("TB biên:", bien.mean())
#tbt tích phần tử không thuộc biên
khong_bien = a[1:-1, 1:-1]
print("TB tích không biên:", khong_bien.mean())

Mảng a:
 [[38 76 12 64 26]
 [98  6 50 71 75]
 [ 9 48 87 42 99]
 [29 48 25  1 20]]
Dòng 1: [98  6 50 71 75]
Cột 2: [12 50 87 25]
Dòng có tổng lớn nhất: 1
Cột có tích nhỏ nhất: 3
Dòng chẵn, cột lẻ:
 [[76 64]
 [48 42]]
TB chẵn ở dòng lẻ: 44.4
TB biên: 44.285714285714285
TB tích không biên: 50.666666666666664


In [4]:
#15
import numpy as np

sv_dtype = np.dtype([
    ('masv', 'U10'),
    ('ten', 'U20'),
    ('namsinh', int),
    ('dtb', float)
])

ds = np.array([
    ('02DH0001', 'Nguyen Van An', 2004, 7.5),
    ('02DH0002', 'Phan Thi Lan',  2003, 4.8),
    ('03CD0003', 'Tran Van Binh', 2004, 6.0),
    ('02DH0004', 'Phan Van Nam',  2002, 5.5),
    ('04TC0005', 'Le Thi Lan',    2005, 3.9)
], dtype=sv_dtype)

# c
print("len lop:", np.sum(ds['dtb'] >= 5))

# d
print("du 20 tuoi:")
for sv in ds[2026 - ds['namsinh'] >= 20]:
    print(sv)

# e
print("he DH:", np.sum([sv['masv'][2:4] == 'DH' for sv in ds]))

# f
print("ten Lan:", np.sum([sv['ten'].split()[-1] == 'Lan' for sv in ds]))

# g
print("ho Phan:", np.sum([sv['ten'].split()[0] == 'Phan' for sv in ds]))

len lop: 3
du 20 tuoi:
('02DH0001', 'Nguyen Van An', 2004, 7.5)
('02DH0002', 'Phan Thi Lan', 2003, 4.8)
('03CD0003', 'Tran Van Binh', 2004, 6.0)
('02DH0004', 'Phan Van Nam', 2002, 5.5)
('04TC0005', 'Le Thi Lan', 2005, 3.9)
he DH: 3
ten Lan: 2
ho Phan: 2
